name = "shortener"
main = "src/worker.ts"
compatibility_date = "2022-11-11"
workers_dev = false
kv_namespaces = [
  { binding = "KV", id = "cb1bc51d54c2469a8822704d6166c95f" }
]

[vars]
FALLBACK_URL = "https://google.ca"
KEY_LENGTH = "5"
WRITE_KEY = "<GENERATE KEY>" # Generate a unique write key https://www.uuidgenerator.net/
