name = "shortener"
main = "src/worker.ts"
compatibility_date = "2022-11-25"
workers_dev = false
kv_namespaces = [
  { binding = "KV", id = "<YOUR KV ID>" }
]

[vars]
FALLBACK_URL = "https://google.ca"
KEY_LENGTH = "8"
WRITE_KEY = ""
